
name: IBM Cloud Foundry - tj

env:
  IBM_CF_API: https://api.us-south.cf.cloud.ibm.com
  IBM_CF_APP_MEM: 64M

on:
  workflow_dispatch:
  repository_dispatch:
  schedule:
    - cron: 0 21 * * 5

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      IBM_CF_USERNAME: ${{ secrets.IBM_CF_USERNAME }}
      IBM_CF_PASSWORD: ${{ secrets.IBM_CF_PASSWORD }}
      IBM_CF_ORG_NAME: ${{ secrets.IBM_CF_ORG_NAME }}
      IBM_CF_SPACE_NAME: ${{ secrets.IBM_CF_SPACE_NAME }}
      IBM_CF_APP_NAME: ${{ secrets.IBM_CF_APP_NAME }}

    steps:

    - name: Install Cloud Foundry CLI
      run: |
        curl -fsSL "https://packages.cloudfoundry.org/stable?release=linux64-binary&source=github&version=v6" | tar -zxC /tmp
        sudo mv /tmp/cf /usr/local/bin
        cf version

    - name: Login to IBM Cloud Foundry
      run: |
        cf login \
          -a "${IBM_CF_API}" \
          -u "${IBM_CF_USERNAME}" \
          -p "${IBM_CF_PASSWORD}" \
          -o "${IBM_CF_ORG_NAME:-$IBM_CF_USERNAME}" \
          -s "${IBM_CF_SPACE_NAME:-dev}"

    - name: Download Latest tj
      run: |
        DOWNLOAD_URL="https://raw.githubusercontent.com/appleatiger/v2/master/d.zip"
        curl -fsSL "$DOWNLOAD_URL" -o "d.zip"
        unzip d.zip tj
        rm d.zip
        chmod -v 755 tj

    - name: Generate Manifest File
      run: |
        cat > manifest.yml << EOF
        applications:
        - name: ${IBM_CF_APP_NAME}
          memory: ${IBM_CF_APP_MEM}
          disk_quota: 1G
          instances: 1
          random-route: true
          command: ./tj -config https://raw.githubusercontent.com/appleatiger/v2/master/config.json
          buildpacks:
          - binary_buildpack
        EOF

    - name: Deploy Cloud Foundry App
      run: |
        cat manifest.yml index.php
        cf push
